FROM mcr.microsoft.com/windows/servercore:ltsc2019

RUN powershell.exe -c 'mkdir -p C:/Go'
WORKDIR C:/Go
COPY . .

RUN powershell.exe -c 'echo "Running inside win2019"'
#RUN go get -d -v ./...
#RUN go install -v ./...

EXPOSE 3000/tcp

CMD ["webapp"]
